<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Ets2SaveEditor.Core\Ets2SaveEditor.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\zlib.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
      <ExcludeFromSingleFile>false</ExcludeFromSingleFile>
      <TargetPath>zlib.dll</TargetPath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="app.ico" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <AssemblyName>TSSaveEditor</AssemblyName>
    <Version>1.2.0</Version>
    <AssemblyVersion>1.2.0.0</AssemblyVersion>
    <FileVersion>1.2.0.0</FileVersion>
    <InformationalVersion>1.2.0</InformationalVersion>
    <Product>TSSaveEditor</Product>
    <Company>motionarium</Company>
  </PropertyGroup>

</Project>
